id: P005503
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:07.577575
source_metadata:
  id: bdr:W1CZ1079
  title: མཁན་བརྒྱུད་རྣམ་གསུམ་བྱོན་ཚུལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    3398e5b4bf964ba98aff5627a905b1e5:
      image_group_id: I1CZ1451
      title: ''
      volume_number: 1
      total_pages: 52
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
